export interface CountryItem {
  name: string;
  code: string;
  flag: string;
  iso: string;
}

export const ALL_COUNTRIES_DATA: CountryItem[] = [
  { name: 'United States', code: '+1', flag: '🇺🇸', iso: 'US' },
  { name: 'United Kingdom', code: '+44', flag: '🇬🇧', iso: 'GB' },
  { name: 'Canada', code: '+1', flag: '🇨🇦', iso: 'CA' },
  { name: 'Australia', code: '+61', flag: '🇦🇺', iso: 'AU' },
  { name: 'Germany', code: '+49', flag: '🇩🇪', iso: 'DE' },
  { name: 'Switzerland', code: '+41', flag: '🇨🇭', iso: 'CH' },
  { name: 'United Arab Emirates', code: '+971', flag: '🇦🇪', iso: 'AE' },
  { name: 'Singapore', code: '+65', flag: '🇸🇬', iso: 'SG' },
  { name: 'France', code: '+33', flag: '🇫🇷', iso: 'FR' },
  { name: 'Netherlands', code: '+31', flag: '🇳🇱', iso: 'NL' },
  { name: 'Japan', code: '+81', flag: '🇯🇵', iso: 'JP' },
  { name: 'Hong Kong', code: '+852', flag: '🇭🇰', iso: 'HK' },
  { name: 'Nigeria', code: '+234', flag: '🇳🇬', iso: 'NG' },
  { name: 'South Africa', code: '+27', flag: '🇿🇦', iso: 'ZA' },
  { name: 'Spain', code: '+34', flag: '🇪🇸', iso: 'ES' },
  { name: 'Italy', code: '+39', flag: '🇮🇹', iso: 'IT' },
  { name: 'Brazil', code: '+55', flag: '🇧🇷', iso: 'BR' },
  { name: 'India', code: '+91', flag: '🇮🇳', iso: 'IN' },
  { name: 'Ireland', code: '+353', flag: '🇮🇪', iso: 'IE' },
  { name: 'New Zealand', code: '+64', flag: '🇳🇿', iso: 'NZ' },
  { name: 'Sweden', code: '+46', flag: '🇸🇪', iso: 'SE' },
  { name: 'Norway', code: '+47', flag: '🇳🇴', iso: 'NO' },
  { name: 'Denmark', code: '+45', flag: '🇩🇰', iso: 'DK' },
  { name: 'Finland', code: '+358', flag: '🇫🇮', iso: 'FI' },
  { name: 'Belgium', code: '+32', flag: '🇧🇪', iso: 'BE' },
  { name: 'Austria', code: '+43', flag: '🇦🇹', iso: 'AT' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹', iso: 'PT' },
  { name: 'Poland', code: '+48', flag: '🇵🇱', iso: 'PL' },
  { name: 'Czech Republic', code: '+420', flag: '🇨🇿', iso: 'CZ' },
  { name: 'Greece', code: '+30', flag: '🇬🇷', iso: 'GR' },
  { name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', iso: 'SA' },
  { name: 'Qatar', code: '+974', flag: '🇶🇦', iso: 'QA' },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼', iso: 'KW' },
  { name: 'Bahrain', code: '+973', flag: '🇧🇭', iso: 'BH' },
  { name: 'Oman', code: '+968', flag: '🇴🇲', iso: 'OM' },
  { name: 'Israel', code: '+972', flag: '🇮🇱', iso: 'IL' },
  { name: 'Turkey', code: '+90', flag: '🇹🇷', iso: 'TR' },
  { name: 'Mexico', code: '+52', flag: '🇲🇽', iso: 'MX' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷', iso: 'AR' },
  { name: 'Chile', code: '+56', flag: '🇨🇱', iso: 'CL' },
  { name: 'Colombia', code: '+57', flag: '🇨🇴', iso: 'CO' },
  { name: 'Peru', code: '+51', flag: '🇵🇪', iso: 'PE' },
  { name: 'Panama', code: '+507', flag: '🇵🇦', iso: 'PA' },
  { name: 'Costa Rica', code: '+506', flag: '🇨🇷', iso: 'CR' },
  { name: 'South Korea', code: '+82', flag: '🇰🇷', iso: 'KR' },
  { name: 'Taiwan', code: '+886', flag: '🇹🇼', iso: 'TW' },
  { name: 'Malaysia', code: '+60', flag: '🇲🇾', iso: 'MY' },
  { name: 'Thailand', code: '+66', flag: '🇹🇭', iso: 'TH' },
  { name: 'Indonesia', code: '+62', flag: '🇮🇩', iso: 'ID' },
  { name: 'Philippines', code: '+63', flag: '🇵🇭', iso: 'PH' },
  { name: 'Vietnam', code: '+84', flag: '🇻🇳', iso: 'VN' },
  { name: 'Kenya', code: '+254', flag: '🇰🇪', iso: 'KE' },
  { name: 'Ghana', code: '+233', flag: '🇬🇭', iso: 'GH' },
  { name: 'Egypt', code: '+20', flag: '🇪🇬', iso: 'EG' },
  { name: 'Morocco', code: '+212', flag: '🇲🇦', iso: 'MA' },
  // Alphabetical Complete World Nations
  { name: 'Afghanistan', code: '+93', flag: '🇦🇫', iso: 'AF' },
  { name: 'Albania', code: '+355', flag: '🇦🇱', iso: 'AL' },
  { name: 'Algeria', code: '+213', flag: '🇩🇿', iso: 'DZ' },
  { name: 'Andorra', code: '+376', flag: '🇦🇩', iso: 'AD' },
  { name: 'Angola', code: '+244', flag: '🇦🇴', iso: 'AO' },
  { name: 'Antigua and Barbuda', code: '+1-268', flag: '🇦🇬', iso: 'AG' },
  { name: 'Armenia', code: '+374', flag: '🇦🇲', iso: 'AM' },
  { name: 'Aruba', code: '+297', flag: '🇦🇼', iso: 'AW' },
  { name: 'Azerbaijan', code: '+994', flag: '🇦🇿', iso: 'AZ' },
  { name: 'Bahamas', code: '+1-242', flag: '🇧🇸', iso: 'BS' },
  { name: 'Bangladesh', code: '+880', flag: '🇧🇩', iso: 'BD' },
  { name: 'Barbados', code: '+1-246', flag: '🇧🇧', iso: 'BB' },
  { name: 'Belarus', code: '+375', flag: '🇧🇾', iso: 'BY' },
  { name: 'Belize', code: '+501', flag: '🇧🇿', iso: 'BZ' },
  { name: 'Benin', code: '+229', flag: '🇧🇯', iso: 'BJ' },
  { name: 'Bermuda', code: '+1-441', flag: '🇧🇲', iso: 'BM' },
  { name: 'Bhutan', code: '+975', flag: '🇧🇹', iso: 'BT' },
  { name: 'Bolivia', code: '+591', flag: '🇧🇴', iso: 'BO' },
  { name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦', iso: 'BA' },
  { name: 'Botswana', code: '+267', flag: '🇧🇼', iso: 'BW' },
  { name: 'Brunei', code: '+673', flag: '🇧🇳', iso: 'BN' },
  { name: 'Bulgaria', code: '+359', flag: '🇧🇬', iso: 'BG' },
  { name: 'Burkina Faso', code: '+226', flag: '🇧🇫', iso: 'BF' },
  { name: 'Burundi', code: '+257', flag: '🇧🇮', iso: 'BI' },
  { name: 'Cambodia', code: '+855', flag: '🇰🇭', iso: 'KH' },
  { name: 'Cameroon', code: '+237', flag: '🇨🇲', iso: 'CM' },
  { name: 'Cape Verde', code: '+238', flag: '🇨🇻', iso: 'CV' },
  { name: 'Cayman Islands', code: '+1-345', flag: '🇰🇾', iso: 'KY' },
  { name: 'Central African Republic', code: '+236', flag: '🇨🇫', iso: 'CF' },
  { name: 'Chad', code: '+235', flag: '🇹🇩', iso: 'TD' },
  { name: 'China', code: '+86', flag: '🇨🇳', iso: 'CN' },
  { name: 'Congo', code: '+242', flag: '🇨🇬', iso: 'CG' },
  { name: 'Congo (DRC)', code: '+243', flag: '🇨🇩', iso: 'CD' },
  { name: 'Croatia', code: '+385', flag: '🇭🇷', iso: 'HR' },
  { name: 'Cyprus', code: '+357', flag: '🇨🇾', iso: 'CY' },
  { name: 'Dominica', code: '+1-767', flag: '🇩🇲', iso: 'DM' },
  { name: 'Dominican Republic', code: '+1-809', flag: '🇩🇴', iso: 'DO' },
  { name: 'Ecuador', code: '+593', flag: '🇪🇨', iso: 'EC' },
  { name: 'El Salvador', code: '+503', flag: '🇸🇻', iso: 'SV' },
  { name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶', iso: 'GQ' },
  { name: 'Estonia', code: '+372', flag: '🇪🇪', iso: 'EE' },
  { name: 'Eswatini', code: '+268', flag: '🇸🇿', iso: 'SZ' },
  { name: 'Ethiopia', code: '+251', flag: '🇪🇹', iso: 'ET' },
  { name: 'Fiji', code: '+679', flag: '🇫🇯', iso: 'FJ' },
  { name: 'French Polynesia', code: '+689', flag: '🇵🇫', iso: 'PF' },
  { name: 'Gabon', code: '+241', flag: '🇬🇦', iso: 'GA' },
  { name: 'Gambia', code: '+220', flag: '🇬🇲', iso: 'GM' },
  { name: 'Georgia', code: '+995', flag: '🇬🇪', iso: 'GE' },
  { name: 'Gibraltar', code: '+350', flag: '🇬🇮', iso: 'GI' },
  { name: 'Greenland', code: '+299', flag: '🇬🇱', iso: 'GL' },
  { name: 'Grenada', code: '+1-473', flag: '🇬🇩', iso: 'GD' },
  { name: 'Guatemala', code: '+502', flag: '🇬🇹', iso: 'GT' },
  { name: 'Guinea', code: '+224', flag: '🇬🇳', iso: 'GN' },
  { name: 'Guyana', code: '+592', flag: '🇬🇾', iso: 'GY' },
  { name: 'Haiti', code: '+509', flag: '🇭🇹', iso: 'HT' },
  { name: 'Honduras', code: '+504', flag: '🇭🇳', iso: 'HN' },
  { name: 'Hungary', code: '+36', flag: '🇭🇺', iso: 'HU' },
  { name: 'Iceland', code: '+354', flag: '🇮🇸', iso: 'IS' },
  { name: 'Iraq', code: '+964', flag: '🇮🇶', iso: 'IQ' },
  { name: 'Ivory Coast', code: '+225', flag: '🇨🇮', iso: 'CI' },
  { name: 'Jamaica', code: '+1-876', flag: '🇯🇲', iso: 'JM' },
  { name: 'Jordan', code: '+962', flag: '🇯🇴', iso: 'JO' },
  { name: 'Kazakhstan', code: '+7', flag: '🇰🇿', iso: 'KZ' },
  { name: 'Kosovo', code: '+383', flag: '🇽🇰', iso: 'XK' },
  { name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬', iso: 'KG' },
  { name: 'Laos', code: '+856', flag: '🇱🇦', iso: 'LA' },
  { name: 'Latvia', code: '+371', flag: '🇱🇻', iso: 'LV' },
  { name: 'Lebanon', code: '+961', flag: '🇱🇧', iso: 'LB' },
  { name: 'Lesotho', code: '+266', flag: '🇱🇸', iso: 'LS' },
  { name: 'Liberia', code: '+231', flag: '🇱🇷', iso: 'LR' },
  { name: 'Libya', code: '+218', flag: '🇱🇾', iso: 'LY' },
  { name: 'Liechtenstein', code: '+423', flag: '🇱🇮', iso: 'LI' },
  { name: 'Lithuania', code: '+370', flag: '🇱🇹', iso: 'LT' },
  { name: 'Luxembourg', code: '+352', flag: '🇱🇺', iso: 'LU' },
  { name: 'Macau', code: '+853', flag: '🇲🇴', iso: 'MO' },
  { name: 'Madagascar', code: '+261', flag: '🇲🇬', iso: 'MG' },
  { name: 'Malawi', code: '+265', flag: '🇲🇼', iso: 'MW' },
  { name: 'Maldives', code: '+960', flag: '🇲🇻', iso: 'MV' },
  { name: 'Mali', code: '+223', flag: '🇲🇱', iso: 'ML' },
  { name: 'Malta', code: '+356', flag: '🇲🇹', iso: 'MT' },
  { name: 'Mauritania', code: '+222', flag: '🇲🇷', iso: 'MR' },
  { name: 'Mauritius', code: '+230', flag: '🇲🇺', iso: 'MU' },
  { name: 'Moldova', code: '+373', flag: '🇲🇩', iso: 'MD' },
  { name: 'Monaco', code: '+377', flag: '🇲🇨', iso: 'MC' },
  { name: 'Mongolia', code: '+976', flag: '🇲🇳', iso: 'MN' },
  { name: 'Montenegro', code: '+382', flag: '🇲🇪', iso: 'ME' },
  { name: 'Mozambique', code: '+258', flag: '🇲🇿', iso: 'MZ' },
  { name: 'Namibia', code: '+264', flag: '🇳🇦', iso: 'NA' },
  { name: 'Nepal', code: '+977', flag: '🇳🇵', iso: 'NP' },
  { name: 'Nicaragua', code: '+505', flag: '🇳🇮', iso: 'NI' },
  { name: 'Niger', code: '+227', flag: '🇳🇪', iso: 'NE' },
  { name: 'North Macedonia', code: '+389', flag: '🇲🇰', iso: 'MK' },
  { name: 'Pakistan', code: '+92', flag: '🇵🇰', iso: 'PK' },
  { name: 'Palestine', code: '+970', flag: '🇵🇸', iso: 'PS' },
  { name: 'Papua New Guinea', code: '+675', flag: '🇵🇬', iso: 'PG' },
  { name: 'Paraguay', code: '+595', flag: '🇵🇾', iso: 'PY' },
  { name: 'Puerto Rico', code: '+1-787', flag: '🇵🇷', iso: 'PR' },
  { name: 'Romania', code: '+40', flag: '🇷🇴', iso: 'RO' },
  { name: 'Rwanda', code: '+250', flag: '🇷🇼', iso: 'RW' },
  { name: 'Saint Kitts and Nevis', code: '+1-869', flag: '🇰🇳', iso: 'KN' },
  { name: 'Saint Lucia', code: '+1-758', flag: '🇱🇨', iso: 'LC' },
  { name: 'Saint Vincent', code: '+1-784', flag: '🇻🇨', iso: 'VC' },
  { name: 'Senegal', code: '+221', flag: '🇸🇳', iso: 'SN' },
  { name: 'Serbia', code: '+381', flag: '🇷🇸', iso: 'RS' },
  { name: 'Seychelles', code: '+248', flag: '🇸🇨', iso: 'SC' },
  { name: 'Sierra Leone', code: '+232', flag: '🇸🇱', iso: 'SL' },
  { name: 'Slovakia', code: '+421', flag: '🇸🇰', iso: 'SK' },
  { name: 'Slovenia', code: '+386', flag: '🇸🇮', iso: 'SI' },
  { name: 'Somalia', code: '+252', flag: '🇸🇴', iso: 'SO' },
  { name: 'Sri Lanka', code: '+94', flag: '🇱🇰', iso: 'LK' },
  { name: 'Suriname', code: '+597', flag: '🇸🇷', iso: 'SR' },
  { name: 'Tanzania', code: '+255', flag: '🇹🇿', iso: 'TZ' },
  { name: 'Trinidad and Tobago', code: '+1-868', flag: '🇹🇹', iso: 'TT' },
  { name: 'Tunisia', code: '+216', flag: '🇹🇳', iso: 'TN' },
  { name: 'Uganda', code: '+256', flag: '🇺🇬', iso: 'UG' },
  { name: 'Ukraine', code: '+380', flag: '🇺🇦', iso: 'UA' },
  { name: 'Uruguay', code: '+598', flag: '🇺🇾', iso: 'UY' },
  { name: 'Uzbekistan', code: '+998', flag: '🇺🇿', iso: 'UZ' },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪', iso: 'VE' },
  { name: 'Zambia', code: '+260', flag: '🇿🇲', iso: 'ZM' },
  { name: 'Zimbabwe', code: '+263', flag: '🇿🇼', iso: 'ZW' },
];

// All country names sorted alphabetically for the Jurisdiction selector
export const ALL_COUNTRY_NAMES: string[] = Array.from(
  new Set(ALL_COUNTRIES_DATA.map((c) => c.name))
).sort((a, b) => a.localeCompare(b));

// Dialing codes sorted by popularity first, then remaining
export const ALL_PHONE_DIAL_CODES: CountryItem[] = ALL_COUNTRIES_DATA;
